networks:
  transcendence:

services:

  # proxy:
  #   depends_on:
  #     - client
  #     - api
  #   container_name: nginx
  #   image: nginx:1.23.3
  #   networks:
  #     - transcendence
  #   ports:
  #     - 443:443
  #   restart: unless-stopped

  frontend:
    container_name: ${FRONTEND_NAME}
    image: ${NODE_VERSION}
    stdin_open: true
    tty: true

    working_dir: /app-${FRONTEND_NAME}
    # Install project dependencies,, then run front
    command: >
            sh -cx "npm install
            && npm run start"
    # Ports should always be strings
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    networks:
      - transcendence
    volumes:
      - ./${FRONTEND_NAME}:/app-${FRONTEND_NAME}
    restart: unless-stopped

  database:
    container_name: postgres
    image: postgres:15.1
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PORT: $POSTGRES_PORT
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - transcendence
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 10s
      timeout: 2s
      retries: 25
      start_period: 2s

  backend:
    depends_on:
      database:
        condition: service_healthy
    container_name: ${BACKEND_NAME}
    image: ${NODE_VERSION}
    working_dir: /app-${BACKEND_NAME}
    # install project dependencies,
    # then run in dev mode
    command: >
            sh -cx "yarn install
            && yarn prisma db push
            && yarn run start:debug"
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${POSTGRES_PORT}/pong?schema=public
    networks:
      - transcendence
    volumes:
      - ./${BACKEND_NAME}:/app-${BACKEND_NAME}
    # stdin_open: true
    # tty: true
    restart: unless-stopped
