version: '3.3'

networks:
  transcendance:

services:

  # proxy:
  #   depends_on:
  #     - client
  #     - api
  #   container_name: nginx
  #   image: nginx:1.23.3
  #   networks:
  #     - transcendance
  #   ports:
  #     - 443:443
  #   restart: unless-stopped

  database:
    container_name: postgres
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - transcendance
    env_file:
      - .env
    restart: unless-stopped

  api:
    depends_on:
      - database
    container_name: api
    image: node:18.13.0-alpine3.16
    working_dir: /app-backend
    # build: ./backend
    command: >
            sh -cx "yarn install
            && yarn global add nodemon
            && nodemon server"
    ports:
      - 3080:3080
    networks:
      - transcendance
    volumes:
      - ./backend:/app-backend
    env_file:
      - .env
    restart: unless-stopped

  client:
    container_name: client
    image: node:18.13.0-alpine3.16
    working_dir: /app-frontend
    # build: ./frontend
    command: >
            sh -cx "npm install
            && npm run start"
    ports:
      - 3000:3000
    networks:
      - transcendance
    volumes:
      - ./frontend:/app-frontend
    # stdin_open: true
    restart: unless-stopped