services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT?:}:3000"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT?:}:3000"
    volumes:
      - ./backend:/backend
      - backend_node_modules:/backend/node_modules/
    networks:
      - private
      - public

volumes:
  frontend_node_modules: {}
  backend_node_modules: {}
