name: Frontend

on:
  - push
  - pull_request

jobs:
  lint:
    name: 'Frotend Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install lint
        working-directory: ./frontend
      - name: ESLint
        run: npm run lint:check
        working-directory: ./frontend